### ISSUE TITLE
Suggested more aggresive Linux clear

### ISSUE THREAD

**Issue by ErezBinyamin** [oliviagallucci/clear-screen#4]
Suggested edit to [clear-screen.py line 10](https://github.com/oliviagallucci/clear-screen/blob/main/clear-screen.py#L10) for [Clearing a terminal screen for real](https://stackoverflow.com/questions/5367068/clear-a-terminal-screen-for-real)

```Python
elif system == 'Linux' or system == 'Darwin':
            os.system('printf "\033c"')
```

**Comment by oliviagallucci** [comment]
Totally! Sorry for the late response time. I'll look into this tomorrow:) 

Thanks for the suggestion!

**Comment by ErezBinyamin** [comment]
Building on this a bit more, you may also want to consider calling `os.name` instead of `platform.system` to determine the system type. 

> [os.name](https://github.com/python/cpython/blob/main/Lib/os.py#L6) is either 'posix' or 'nt'.


## posix
Clearing the screen on _posix_ systems is a [solved problem](https://stackoverflow.com/questions/24754406/how-can-you-clear-reset-the-screen-in-unix-posix-not-curses-newlines) who's solution is:
```python
os.system('printf "\033c"')
```

## nt
Clearing the screen on _nt_ systems is also solved. You already solved it too! it's just `cls`
```python
os.system('cls')
```

**Comment by oliviagallucci** [comment]
Thank you so much! This is super helpful! I'll do that.

I'll @ ya when I update it :D

**Comment by oliviagallucci** [comment]
Thanks again! @ErezBinyamin
